### PR TITLE
Readings in banzhuren liu xinwu

### LINKED ISSUE #414: Narrative status in The Class Teacher
Hello @LenaHenningsen and @duncdrum 
We have either 'NarrativePosition' or 'SocialPosition' to give the narrative status of the fictional persons.

Martyr
Middle character
Ordinary person
Class enemy
Participant in the underground struggle

or

higher cadre
lower cadre
intellectual
executive
high-ranking military officer
middle class
worker
peasant
common soldier

I just started to add some info on protagonists in _The Class Teacher_ by Liu Xinwu and was wondering how to deal with their narrative status, which are described as "activist"or "protagonist".
I'm not sure to which table I should add them.

### PR DESCRIPTION
**Pull request by mira-gruenwald**
See #415   .
Close #414  .

### Checklist
-   The title line explains what these changes do
-   All my changes are marked in the `last_modfied` column
-   The PR has no merge conflicts
-   Travis checks are passing

### CODE REVIEW

**Comment by LenaHenningsen** [comment]
Hi @mira-gruenwald, thank you for this. From what I see, only a minor thing: there is one AT60 in row 1145 - it may be splitting hairs, but to plan to do something is different from doing it; right? I think that we can leave it like this, if there is no easy solution - but the impetus might be slightly different.
Lena

**Comment by mira-gruenwald** [comment]
> Hi @mira-gruenwald, thank you for this. From what I see, only a minor thing: there is one AT60 in row 1145 - it may be splitting hairs, but to plan to do something is different from doing it; right? I think that we can leave it like this, if there is no easy solution - but the impetus might be slightly different.
> Lena

Hey Lena,
right...I could change it to AT05 "to mention" . What do you think? Or we create a new type, to plan sth. ?

**Comment by LenaHenningsen** [comment]
Well, here, the really nice thing is prospect of COLLECTIVE reading. Maybe a new category like to plant to read collectively? (For any counting, if I understand it correctly that could then be added to all AT60).

Thanks a lot!


 

Von: Mira Grünwald <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Montag, 2. Dezember 2019 um 17:02
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Review requested <review_requested@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Readings in banzhuren liu xinwu (#416)

 

Hi @mira-gruenwald, thank you for this. From what I see, only a minor thing: there is one AT60 in row 1145 - it may be splitting hairs, but to plan to do something is different from doing it; right? I think that we can leave it like this, if there is no easy solution - but the impetus might be slightly different.
Lena

Hey Lena,
right...I could change it to AT05 "to mention" . What do you think? Or we create a new type, to plan sth. ?

**Comment by duncdrum** [comment]
I like a new actype `planning to read` a common thing among academics, also `planning to read collectively` would make another good acttype. Since organizing and scheduling reading-groups is sort of different from placing something at the bottom of the ever growing reading pile.

**Comment by LenaHenningsen** [comment]
Then to plan to read collectively fits pretty well here; plus it points to the entire realm of instructive / educative reading that Damian is working on. 

 

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Montag, 2. Dezember 2019 um 17:27
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Review requested <review_requested@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Readings in banzhuren liu xinwu (#416)

 

I like a new actype planning to read a common thing among academics, also planning to read collectively would make another good acttype. Since organizing and scheduling reading-groups is sort of different from placing something at the bottom of the ever growing reading pile.

**Comment by duncdrum** [comment]
ok i ll merge this into lit then, so you can start working on a new branch based from there.

**Pull request merged**
