### PR TITLE
andersen references in Open Love Letters

### LINKED ISSUE #366: Fictional Reading Acts
@LenaHenningsen @duncdrum @damianodamiani @HUANG0421 @EveYLin 

Some questions came up during our last teleconference regarding the integration of fictional reading acts to the data.

Can we put fictional and non-fictional acts together or rather how to separate them?

Can non-fictional acts be recorded in fictional texts?

And what should we do with the categorization of SecondarySources in 01 informational works, 02 literary non-fiction, 03 fiction, as we have it in Act.csv ?

### PR DESCRIPTION
**Pull request by LenaHenningsen**
> Pull-requests should be ready to merge, that is free of conflicts, and they should pass our testsuite. If you require a specific reviewer you can request a review on the right.

### Please indicate issues related to this PR (if any)
See # .
Close #366

### Checklist
-   The title line explains what these changes do
-   All my changes are marked in the `last_modfied` column
-   The PR has no merge conflicts
-   Travis checks are passing

### CODE REVIEW

**Comment by LenaHenningsen** [comment]
Travis looks happy...

**Comment by duncdrum** [comment]
looks good, i would however prefer to incorporate fictional reading acts in the next major version, so could we add further commits into this branch and then do a larger merge in about 2 weeks when we collectively move from 1.0.0 to 2.0.0?

**Comment by LenaHenningsen** [comment]
If that does not create major mafan, I don’t care… this would mean that I would continue to add a couple more into this branch and close each session with a commit, right?

(Will be offline most of next week anyhow because of AAS)

Thanks much

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Dienstag, 12. März 2019 um 12:08
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [readchina/ReadingData] andersen references in Open Love Letters (#364)

 

looks good, i would however prefer to incorporate fictional reading acts in the next major version, so could we add further commits into this branch and then do a larger merge in about 2 weeks when we collectively move from 1.0.0 to 2.0.0?

**Comment by duncdrum** [comment]
exactly

**Comment by duncdrum** [comment]
Please use the 2.0 fiction branch to continue this work. All changes from here should be in that branch.

**Pull request closed without merging**
